#MODEL_NAME = 'trillionlabs/Trillion-7B-preview'
MODEL_NAME = 'LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct'
MAX_TOKENS = 1024
SEGMENT_MODE = True
BASE = 'Role: You are a sequential text processing tool. Output only the requested text itself, do not add any other explanations or comments.'
REQUEST = 'Condense this book segment into a short, clear, simple, readable encapsulation. Present the central causal mechanism rather than including every detail. Just present a summary of the main point briefly. Keep it short. Assume the context is known and does not have to be repeated. Try to interpret it instead of repeating it verbatim. Do not soften rough aspects. Limit output to maybe 30 words. Never use any introductory phrase whatsoever: no “the core mechanism was”, no “basically”, no “it was about”, no “the point is”, no “the text argues”, no “essentially”.'
MEMORY = False
SIMPLE_MEMORY = True
PRINT = True
THINKING = False
MEMORY_JSON = False
SIMPLE_MEMORY_JSON = False
REQUEST_JSON = 'You process all sentences from a book one by one. This sentence has been extracted from a book and some words contain erroneous additional many spaces. Remove these additional spaces inside words and write the sentene with no other change. If the text does not require any changes, leave it exactly as it is.'
MAX_TEXT_CHARS = 500
