#MODEL_NAME = "trillionlabs/Trillion-7B-preview"
MODEL_NAME = "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct"
MAX_TOKENS = 1024
SEGMENT_MODE = True
BASE = "You are a text processing model. Output only the processed text itself, do not add other explanations or comments.\n"
REQUEST = "Write one sentence that presentes the central theme of this segment, like a summary, but focus on what is stark or unusual."
MEMORY = False
PRINT = True
THINKING = False
